# Introduction to TensorFlow

In [3]:
import tensorflow as tf

In [9]:
a=tf.constant([2])
b=tf.constant([3])
c=tf.add(a,b)
#c=a+b is also a way to define the sum of the terms

Create a session to run our tensorflow code

In [5]:
session=tf.Session()

Let's run our session to get the result of 'c'

In [6]:
result=session.run(c)
result

array([5])

In [7]:
session.close()

To avoid closing a session every time we use the 'with', so after running our code it will close automatically.

In [12]:
with tf.Session() as session:
    result=session.run(c)
    print(result)

[5]


## Dimensions

In [13]:
graph2 = tf.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,2])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = sess.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = sess.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



<b>Convolutional Neural Network (CNN) </b>= Use a certain data to classify what you want. e.g. Malignant Cancer, Cat or dog, Face Recognition, Coloring black and white photos, creating canvas painting on a photo.<br><br>
<b>Recurrent Neural Network (RNN) </b>= Learn by itself and based on probability give us a result. e.g. Sentimental Analysis, Recognize Voice<br><br>
<b>Restricted Boltzman Machine (RBM) </b>= Used to find patterns in a unsupervised manner and automatically extract meaningful features from a given input without need to label them. e.g. Feature Extraction/Learning, Dimensionality Reduction, Pattern Recognition, Recommender System (Collaborative Filtering), Handling Missing Values, Topic Modeling<br><br>
<b>Deep Belief Network (DBN) </b>= Network to solve backpropagation using multiple RBM's which causes local mininum or vanishing gradient issues in the learning process. (Don't need a big set label data to train) e.g. Classification (Image Recognition)<br><br>
<b>Auto Encoders </b>= Like RBM but try to recreate a given input but with a slight different architecture extracting the most valueable informationg from the data. e.g. Unsupervised Tasks, Dimensionality Reduction, Feature Extraction, Imagem Recognition