# Numpy

In [2]:
#Importando o numpy
import numpy as np

In [2]:
#Estrutura Unidimensional
a1=np.array(['Spark','Hadoop','Python','R'])

In [3]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

### Array com tipo de lista diferente

In [5]:
a2=np.array([['Altura','Largura','Profundidade'],[42,78,10]])

In [6]:
a2

array([['Altura', 'Largura', 'Profundidade'],
       ['42', '78', '10']], dtype='<U12')

In [7]:
a3=np.array([[10,20,30],[40,50,60]])

In [8]:
a3

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
#Tamanho do array
print(a1.shape)
print(a2.shape)

(4,)
(2, 3)


In [16]:
#Dimensão do array
print(a1.ndim)
print(a2.ndim)

1
2


In [19]:
#Metodo max tras o máximo do array porém não em arrays com tipagem diferente dentro do array
a3.max()

60

## Método Arange

In [21]:
array=np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
#Usando como em um for
array=np.arange(0,100,10)
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Criando estrutura de dados com linspace

In [30]:
#Diferença entre linspace e arange é que o ultimo argumento passado por arange é o passo e em linspace é o número de elementos
#do vetor.
#Criará elemento neste intervalo porém aleatórios
matriz=np.linspace(0,10,20)
matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
matriz=np.linspace(0,10,5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
matriz=np.linspace(0,5,5)
matriz

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

## Estrutura de matrizes

In [28]:
#numpy.zeros - Cria tudo com 0
matriz=np.zeros((10,10))
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
#numpy.ones - Cria tudo com 1
matriz=np.ones((3,3))
print(matriz)
matriz=np.full((3,3),True,dtype=bool)
print(matriz)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [31]:
#numpy.eye - Matriz do tipo identity - Apenas com a diagonal principal igual a 1
matriz=np.eye(10)
matriz

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
#numpy.diag - Matriz composta de zeros e com os número que estaram dentro da função irão para a diagonal principal
#O tamanho da matriz é calculado automaticamente
matriz=np.diag((2,3,5,8,10,23,454,54,12))
matriz

array([[  2,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   3,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   5,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   8,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  10,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,  23,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 454,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  54,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  12]])

In [ ]:
#numpy.empty - Cria matriz vazia
matriz=np.empty((5,5))
matriz

## numpy.tile

In [37]:
#Duplica os elementos da linha
np.tile(np.array([[1,2],[2,3],[5,6]]),3)

array([[1, 2, 1, 2, 1, 2],
       [2, 3, 2, 3, 2, 3],
       [5, 6, 5, 6, 5, 6]])

In [38]:
#A mesma coisa porém multiplica a coluna também
#Caso o segundo argumento seja maior que um número apenas, deve ser passado como tupla
np.tile(np.array([[1,2],[2,3],[5,6]]),(3,6))

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])

# Tipagem de Dados

In [39]:
#Podemos determinar o tipo do array por parametro, caso não passe o próprio python determina qual o tipo
a=np.array([-10,20,30,40,50],dtype='float')
a

array([-10.,  20.,  30.,  40.,  50.])

In [40]:
#Verificar o tipo de array
a.dtype

dtype('float64')

# Cast de array - Transformar um tipo em outro

In [42]:
f=np.array([-9,10,20.7])
f.dtype

dtype('float64')

In [44]:
f.astype(int)

array([-9, 10, 20])

# Criando array com operação aritmética

In [50]:
array=np.arange(10,25)*5
print(array)
array_pot=np.arange(1,6)**2
print(array_pot)

[ 50  55  60  65  70  75  80  85  90  95 100 105 110 115 120]
[ 1  4  9 16 25]


# Operação aritmética com dois arrays

In [51]:
a=np.arange(0,10)
b=np.arange(0,10)+1

In [52]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
#Soma
a+b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [55]:
#Subtração
a-b

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [56]:
#Divisão
a/b

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [57]:
#Multiplicação
a*b

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [58]:
#Comparação
a==b

array([False, False, False, False, False, False, False, False, False,
       False])

In [59]:
a<b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Dot Product

In [61]:
a=np.array([2,4,6])
b=np.array([4,6,10])

In [63]:
a*b

array([ 8, 24, 60])

In [62]:
#Soma dos produtos gerados pela multiplicação de indice a indice
np.dot(a,b)

92

## Concatenate

In [65]:
np.concatenate([a,b])

array([ 2,  4,  6,  4,  6, 10])

In [67]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate([a,b])

array([[1, 2],
       [3, 4],
       [5, 6]])

# Exercícios

In [20]:
#Verificando os impares de um array
array=np.arange(0,10)
array[array%2!=0]

array([1, 3, 5, 7, 9])

In [28]:
#Colocando -1 em valores impares
array=np.arange(0,10)
array[array%2!=0]=-1
array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [32]:
#Substituindo valores impares por -1 mas sem alterar o array
array=np.arange(0,10)
out=np.where(array%2!=0,-1,array)
print(array)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [36]:
#Trocando o shape do array
array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
#Pegando items em comum entre duas arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [39]:
#Diferença entre dois arrays
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [46]:
#Trocando colunas
array=np.arange(9).reshape(3,3)
array[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [47]:
#Trocando linhas
array[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [48]:
#Invertendo a ordem das linhas
array[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [55]:
#Invertendo a ordem das colunas
array[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [57]:
'''
1. Crie um array com 10 elementos usando a função arange;
2. Transforme esse array de 1D (1x10) para 2D (2x5) usando a função
reshape;
3. Crie duas matrizes a partir de dois arrays;
4. Crie duas matrizes e realize a multiplicação das mesmas.
'''
arr=np.arange(0,10).reshape(2,5)
arr2=np.arange(10,20).reshape(5,2)
matriz=np.mat(arr)
matriz2=np.mat(arr2)
print(np.dot(matriz,matriz2))

[[160 170]
 [510 545]]


# Matriz

In [3]:
#Matriz no numpy pode ser apenas bidimensional
A = np.matrix([[1,2],[3,4]])
B = np.matrix([[5,6],[7,8]])
Z = np.array([
    [[2,6],[8,4]],
    [[2,6],[8,4]],
    [[2,6],[8,4]]
])
Y = np.array([2,6,8,4])

In [4]:
Z.shape

(3, 2, 2)

In [5]:
Y.shape

(4,)

In [6]:
A.shape

(2, 2)

### Operações Aritméticas com Matriz

In [7]:
print(A+B)

[[ 6  8]
 [10 12]]


In [8]:
print(B+3)

[[ 8  9]
 [10 11]]


In [9]:
print(A*A)

[[ 7 10]
 [15 22]]


In [10]:
#Multiplicar indice por indice
print(np.multiply(A,A))

[[ 1  4]
 [ 9 16]]


### Matriz Inversa

In [11]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


### Matriz Transposta

In [13]:
#Troca linha por coluna
A.T

matrix([[1, 3],
        [2, 4]])

# Transposição e Reshaping

In [14]:
a=np.array([[10,20,30],[40,50,60]])

In [15]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [16]:
a.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [17]:
np.transpose(a)

array([[10, 40],
       [20, 50],
       [30, 60]])

## Broadcasting

In [19]:
b=np.array([[100,200,300]])

In [20]:
b

array([[100, 200, 300]])

In [21]:
b.T

array([[100],
       [200],
       [300]])

In [22]:
b.T + b

array([[200, 300, 400],
       [300, 400, 500],
       [400, 500, 600]])

## Convertendo Matrizes em Arrays

In [23]:
a=np.array([np.arange(10,60,10,),np.arange(100,150,10)])

In [24]:
a

array([[ 10,  20,  30,  40,  50],
       [100, 110, 120, 130, 140]])

In [25]:
a.shape

(2, 5)

In [26]:
#Pegou cada linha e colocou em apenas um array
a.ravel()

array([ 10,  20,  30,  40,  50, 100, 110, 120, 130, 140])

In [27]:
a.T.ravel()

array([ 10, 100,  20, 110,  30, 120,  40, 130,  50, 140])

## Operadores Lógicos

In [28]:
array=np.random.randint(1,10,size=(4,4))

In [29]:
array

array([[7, 7, 5, 9],
       [2, 8, 2, 8],
       [5, 7, 6, 6],
       [4, 7, 1, 1]])

In [30]:
np.any((array%7)==0)

True

In [33]:
np.all((array%1)==1)

False

In [34]:
np.all(array<8)

False

## Resharping

In [35]:
array=np.arange(1,16)

In [36]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
array.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Ordernar Arrays

In [45]:
array=np.array([
    [3,2],
    [10,-1]
])

In [40]:
array

array([[ 3,  2],
       [10, -1]])

In [43]:
#Axis ordenando por linha = axis=1
array.sort(axis=1)

In [44]:
array

array([[ 2,  3],
       [-1, 10]])

In [46]:
#Axis ordenando por coluna = axis=0
array.sort(axis=0)

In [47]:
array

array([[ 3, -1],
       [10,  2]])