# K-Means

K-Means work in two steps:<br/>
1.Assign: Creating some points to clustering<br/>
2.Optimize: Finding the best position for the center point

https://www.naftaliharris.com/blog/visualizing-k-means-clustering/

n_clusters=8(default)<br/>
max_iter=300(default)<br/>
n_init=10(default)

Limitations:<br/>
The output for any fixed training set will never be the same

In [1]:
from sklearn.cluster import KMeans

In [2]:
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0],[10, 2], [10, 4], [10, 0]])

In [3]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

In [4]:
kmeans.labels_

array([1, 1, 1, 0, 0, 0])

In [11]:
clust_labels = kmeans.predict(X)

array([1, 1, 1, 0, 0, 0])

In [6]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])